config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do


  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  get '/servers' => 'servers#index'
  get '/servers/hartbeat' => 'servers#hartbeat'

  # search
  get '/games/matchmaking_status' => 'games#matchmaking_status'
  post '/games/start_matchmaking' => 'games#start_matchmaking'
  post '/games/stop_matchmaking' => 'games#stop_matchmaking'

  resources :games

  root 'pages#home'
end

app/models/server.rb
class Server < ActiveRecord::Base
end

app/controllers/servers_controller.rb
class ServersController < ActionController::Base

  before_action :set_servers, only: [:index]
  before_action :set_searches, only: [:index]

  # GET /servers
  def index

  end

  # GET /servers/1
  def show
  end

  # GET/PUT /servers/hartbeat
  def hartbeat
    $redis.setex("server_#{server_params[:uuid]}", 10, server_params.to_json)
    render :json=>{succeed:true}
  end

  private
    # Only allow a trusted parameter "white list" through.
    def server_params
      params.permit(:uuid, :addr, :port, :status)
    end

    def set_servers
      @servers = $redis.keys('server_*').map { |k| JSON.parse($redis.get(k)) }
    end

    def set_searches
      @searches = $redis.keys('search_*').map { |k| JSON.parse($redis.get(k)) }
    end

end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.haml
= simple_form_for(@server) do |f|
  = f.error_notification

  .form-inputs
    = f.input :uuid
    = f.input :addr
    = f.input :port
    = f.input :status
    = f.input :intend

  .form-actions
    = f.button :submit

app/views/servers/edit.html.haml
%h1 Editing server

= render 'form'

= link_to 'Show', @server
\|
= link_to 'Back', servers_path

app/views/servers/index.html.haml
%h1 Listing servers

%table
  %tr
    %th Uuid
    %th Addr
    %th Port
    %th Status
    %th

  - @servers.each do |server|
    %tr
      %td= server['uuid']
      %td= server['addr']
      %td= server['port']
      %td= server['status']

%br

%table
  %tr
    %th User
    %th Session

  - @searches.each do |search|
    %tr
      %td= search['user_id']
      %td= search['session']

%br

app/views/servers/new.html.haml
%h1 New server

= render 'form'

= link_to 'Back', servers_path

app/views/servers/show.html.haml
%p#notice= notice

%p
  %b Uuid:
  = @server.uuid
%p
  %b Addr:
  = @server.addr
%p
  %b Port:
  = @server.port
%p
  %b Status:
  = @server.status
%p
  %b Intend:
  = @server.intend

= link_to 'Edit', edit_server_path(@server)
\|
= link_to 'Back', servers_path