config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do


  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  get '/servers' => 'servers#index'
  get '/servers/hartbeat' => 'servers#hartbeat'

  # search
  get '/games/matchmaking_status' => 'games#matchmaking_status'
  post '/games/start_matchmaking' => 'games#start_matchmaking'
  post '/games/stop_matchmaking' => 'games#stop_matchmaking'

  resources :games

  root 'pages#home'
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  layout 'game', only: [:index]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new

  end


  def matchmaking_status
    search_json = $redis.get("search_#{current_user.id}")
    if search_json.nil?
      render json:{active:false,searching:false,status:''}
    else
      $redis.expire("search_#{current_user.id}",120)
      search = JSON.parse(search_json)
      if search['session'].nil?
        render json:{active:true,searching:true,status:'searching...'}
      else
        render json:{active:true,searching:false,session:search['session'],status:'game '}
      end
    end
  end

  def start_matchmaking
    $redis.setex("search_#{current_user.id}", 120, {user_id:current_user.id, session:nil}.to_json)
    render nothing: true
  end

  def stop_matchmaking
    $redis.del("search_#{current_user.id}")
    render nothing: true
  end


  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:uuid, :server_uuid, :server_addr, :server_port, :started_at, :over_at)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= simple_form_for(@game) do |f|
  = f.error_notification

  .form-inputs
    = f.input :uuid
    = f.input :server_uuid
    = f.input :server_addr
    = f.input :server_port
    = f.input :started_at
    = f.input :over_at

  .form-actions
    = f.button :submit

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1 Listing games

%table
  %tr
    %th Uuid
    %th Server uuid
    %th Server addr
    %th Server port
    %th Started at
    %th Over at
    %th
    %th
    %th

  - @games.each do |game|
    %tr
      %td= game.uuid
      %td= game.server_uuid
      %td= game.server_addr
      %td= game.server_port
      %td= game.started_at
      %td= game.over_at
      %td= link_to 'Show', game
      %td= link_to 'Edit', edit_game_path(game)
      %td= link_to 'Destroy', game, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= button_to 'Search for Game', new_game_path, class:'btn', method: :get

app/views/games/new.html.haml
%h1 Create game

%d

//= button_to 'Stop', games_path, remote: true, class: 'btn btn-primary', :form => {:'data-loading-text' => 'wait ...'}

= button_to 'Do Search', { controller: '/games', action: 'start_matchmaking' }, id: 'matchmaking_start_btn', class: 'btn', remote: true

app/views/games/show.html.haml
- content_for(:title, 'MMO Starter Kit Demo Web Application')
- content_for(:head) do
  = stylesheet_link_tag 'game/unity_player', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'game/unity_player', 'data-turbolinks-track' => true

%p#notice= notice

%h1 MMO Starter Kit Demo
= unity_player

= link_to 'Back', games_path